### ISSUE TITLE
cookieStore.remove instead of cookieStore.delete

### ISSUE THREAD

**Issue by pwnall** [WICG/async-cookies-api#46]
`delete` is a keyword in JavaScript and C++. Even though it can be safely used in ES5+, it's still less ergonomic, as it doesn't work well with simple syntax highlighters and older tools. Let's follow the suit of APIs that use `remove`, please.

**Comment by mkruisselbrink** [comment]
FWIW at least IndexedDB and Cache both use `delete` to delete individual records (not saying that using `remove` doesn't make sense, as you say at least domstorage uses some variant of remove, and I assume there are other APIs that use remove as well).

**Comment by domenic** [comment]
-1, delete is the standard across most collections in JS (cf. Map and Set and all maplike and setlikes in IDL).

**Comment by pwnall** [comment]
@domenic That's a pretty good argument.
